USER_SERVICE_PORT: 8082

PRODUCTION_DB_HOST: localhost
PRODUCTION_DB_PORT: 5433
PRODUCTION_DB_NAME: telegram_vpn
PRODUCTION_DB_USER: admin
PRODUCTION_DB_PASSWORD: admin

REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PASSWORD: "IWpw9JisuLnGUabcktuxcH5hK6jFRXju"
CACHE_TTL: 600000

INTERNAL_SECRET: "53a41724a2428714e21b2cbcbb19ce1ff62f4deb322037575f15f450791d54c3"
ADMIN_USER_IDS: "858441917"

LOG_LEVEL: INFO
VPN_LOG_LEVEL: DEBUG
HIBERNATE_LOG_LEVEL: DEBUG
SHOW_SQL: true

JPA_DDL_AUTO: validate
FLYWAY_ENABLED: true
MONITORING_ENDPOINTS: "*"