version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vpn-postgres-local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: geovpn_db
    ports:
      - "5432:5432"
    volumes:
      - vpn_postgres_local_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d geovpn_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vpn-redis-local
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - vpn_redis_local_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  vpn_postgres_local_data:
  vpn_redis_local_data: