ALTER TABLE servers ADD COLUMN panel_username VARCHAR(100);
ALTER TABLE servers ADD COLUMN panel_password VARCHAR(100);
ALTER TABLE servers ADD COLUMN panel_inbound_id INTEGER;
ALTER TABLE servers ADD COLUMN panel_path VARCHAR(255);
ALTER TABLE servers ADD COLUMN panel_port INTEGER DEFAULT 8080;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='servers' AND COLUMN_NAME='grpc_port') THEN
ALTER TABLE servers ADD COLUMN grpc_port INTEGER DEFAULT 62789;
END IF;
END $$;