server:
  port: ${BOT_PORT}

spring:
  application:
    name: telegram-bot
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    channel-id: ${TELEGRAM_CHANNEL_ID}
    channel-url: ${TELEGRAM_CHANNEL_URL}

services:
  internal-secret: ${INTERNAL_SECRET}
  user-service:
    url: ${USER_SERVICE_URL}
  vpn-config-service:
    url: ${VPN_CONFIG_SERVICE_URL}

app:
  miniapp-url: ${MINIAPP_URL}

logging:
  level:
    com.vpn.bot: INFO
    org.telegram: INFO