server:
  port: ${GATEWAY_PORT}
  error:
    include-message: always

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: ${ALLOWED_ORIGINS}
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/v1/users/**, /api/v1/devices/**, /api/v1/admin/dashboard/**, /api/v1/admin/users/**
        - id: vpn-config-service
          uri: ${VPN_CONFIG_SERVICE_URL}
          predicates:
            - Path=/api/v1/configs/**, /api/v1/admin/device-limits/**, /api/v1/subscription/**
        - id: server-management-service
          uri: ${SERVER_MGM_SERVICE_URL}
          predicates:
            - Path=/api/v1/servers/**, /api/v1/traffic/**
        - id: billing-service
          uri: ${BILLING_SERVICE_URL}
          predicates:
            - Path=/api/v1/billing/**, /api/v1/transactions/**

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

service:
  jwt:
    secret: ${JWT_SECRET}
  security:
    internal-secret: ${INTERNAL_SECRET}