server:
  port: 8080

GATEWAY_PORT: 8080

REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PASSWORD: "IWpw9JisuLnGUabcktuxcH5hK6jFRXju"

USER_SERVICE_URL: http://localhost:8082
VPN_CONFIG_SERVICE_URL: http://localhost:8083
SERVER_MGM_SERVICE_URL: http://localhost:8084
BILLING_SERVICE_URL: http://localhost:8085

ID_ROUTES_USER_SERVICE: user-service
ID_ROUTES_VPN_CONFIG_SERVICE: vpn-config-service
ID_ROUTES_SERVER_MGM_SERVICE: server-management-service
ID_ROUTES_BILLING_SERVICE: billing-service

PATH_USER_SERVICE: "/api/v1/users/**, /api/v1/devices/**, /api/v1/admin/dashboard/**, /api/v1/admin/users/**"
PATH_VPN_CONFIG_SERVICE: "/api/v1/configs/**, /api/v1/admin/device-limits/**, /api/v1/subscription/**"
PATH_SERVER_MGM_SERVICE: "/api/v1/servers/**,/api/v1/traffic/**"
PATH_BILLING_SERVICE: "/api/v1/billing/**,/api/v1/transactions/**"

JWT_SECRET: "uW9qAlq/RnfpA1iSdRmHtFsECIDK8i7wv1GUtmYCHG/9RliQzAxx3szjOFtfSaZg+DmLcbluvS1yr7vOsiApjg=="
JWT_EXPIRATION: 3600000
JWT_REFRESH_EXPIRATION: 604800000

INTERNAL_SECRET: "53a41724a2428714e21b2cbcbb19ce1ff62f4deb322037575f15f450791d54c3"

ALLOWED_ORIGINS: http://localhost:5173
SECURITY_OPEN_ENDPOINTS: "/api/v1/auth/**,/api/v1/webhooks/**,/actuator/**,/fallback,/api/v1/admin/**"

MONITORING_ENDPOINTS: "*"


logging:
  level:
    com.vpn.gateway: DEBUG
    org.springframework.cloud.gateway: TRACE

service:
  jwt:
    secret: "uW9qAlq/RnfpA1iSdRmHtFsECIDK8i7wv1GUtmYCHG/9RliQzAxx3szjOFtfSaZg+DmLcbluvS1yr7vOsiApjg=="
  security:
    internal-secret: "53a41724a2428714e21b2cbcbb19ce1ff62f4deb322037575f15f450791d54c3"