SERVER_MGM_PORT: 8084

PRODUCTION_DB_HOST: postgres
PRODUCTION_DB_PORT: 5432
PRODUCTION_DB_NAME: telegram_vpn_dev
PRODUCTION_DB_USER: vpn_admin
PRODUCTION_DB_PASSWORD: admin

JPA_DDL_AUTO: validate

INTERNAL_SECRET: "53a41724a2428714e21b2cbcbb19ce1ff62f4deb322037575f15f450791d54c3"
INTERNAL_CHECK_ENABLED: true
ADMIN_USER_IDS: "858441917,970667053"

VPN_HEALTH_CHECK_MS: 10000
VPN_TIMEOUT_MS: 2000
XRAY_GRPC_PORT: 10085

MONITORING_ENDPOINTS: "*"